<?php

// "Marketing e Lead": the commercial pipeline gathered under one
// collapsible parent — the operational records (projects, campaigns,
// leads) together with their own lookup tables (pipeline/lead statuses).
// A route-less parent with children renders as a collapsible group; it
// is dropped automatically when the actor can see none of its children.
return [
    'key' => 'marketing-leads',
    'label' => 'navigation.marketingLeads',
    'icon' => 'megaphone',
    'route' => null,
    'permission' => null,
    'children' => [
        [
            // Projects (spec 0023): operational record grouping a
            // classification (status/business function/state/product
            // category) and, optionally, its budget-constrained campaigns.
            'key' => 'projects',
            'label' => 'navigation.projects',
            'icon' => 'layers',
            'route' => '/projects',
            'permission' => 'projects.view',
        ],
        [
            // Campaigns (spec 0023): standalone or project-linked
            // (read-through classification/budget, BR-2/BR-3).
            'key' => 'campaigns',
            'label' => 'navigation.campaigns',
            'icon' => 'waypoints',
            'route' => '/campaigns',
            'permission' => 'campaigns.view',
        ],
        [
            // Leads (spec 0024): a contact (Referent) generated by a
            // Campaign, optionally scoped to a Sede/Fonte/Operatore.
            // Navigable parent: clicking it opens the list (/leads); the
            // dedicated import module hangs beneath it (user decision
            // 2026-07-16).
            'key' => 'leads',
            'label' => 'navigation.leads',
            'icon' => 'user-plus',
            'route' => '/leads',
            'permission' => 'leads.view',
            'children' => [
                [
                    // Import (spec 0034): the history table of every
                    // import run plus the multi-step wizard. Gated by the
                    // lead module's `leads.import` ability (the former
                    // dedicated `import-runs.*` set was a duplicate,
                    // removed 2026-07-17).
                    'key' => 'imports',
                    'label' => 'navigation.imports',
                    'icon' => 'file-up',
                    'route' => '/imports',
                    'permission' => 'leads.import',
                ],
            ],
        ],
        [
            // Pipeline statuses (spec 0023): the Project/Campaign
            // classification pick-list, delete-guarded (BR-4).
            'key' => 'pipeline-statuses',
            'label' => 'navigation.pipelineStatuses',
            'icon' => 'tag',
            'route' => '/pipeline-statuses',
            'permission' => 'pipeline-statuses.view',
        ],
    ],
];
