<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Backend-driven navigation (Level 0)
    |--------------------------------------------------------------------------
    |
    | Declarative menu tree. NavigationService filters these items by the
    | current user's permissions (Spatie). The frontend just renders what it
    | receives — it never decides visibility.
    |
    | Item shape:
    |   - key:        stable identifier (string)
    |   - label:      i18n key resolved by the frontend (e.g. "navigation.users")
    |   - icon:       icon name the frontend maps to a component (nullable)
    |   - route:      frontend route (nullable for pure groups)
    |   - permission: required permission, or null = any authenticated user
    |   - role:       (optional, spec 0013) required Spatie role name — item is
    |                 visible ONLY to a user holding it (in ADDITION to the
    |                 permission check above, if any). Omit for ordinary items;
    |                 never used by SyncPermissions (it has nothing to do with
    |                 the permission catalogue).
    |   - type:       'item' (default) or 'section'. A 'section' is a labeled
    |                 separator: the frontend renders its children as flat,
    |                 sibling links under a group label — NOT as a collapsible
    |                 parent. Omit for ordinary items.
    |   - children:   nested items (optional)
    |
    | A group/section (route = null) with no visible children is removed
    | automatically by NavigationService.
    |
    | NOTE: hiding a menu item is UX only. Every endpoint must still enforce
    | authorization server-side via Policies/permissions.
    |
    */

    'items' => [
        [
            'key' => 'dashboard',
            'label' => 'navigation.dashboard',
            'icon' => 'layout-dashboard',
            'route' => '/dashboard',
            'permission' => null,
        ],

        // "Marketing e Lead": the commercial pipeline gathered under one
        // collapsible parent — the operational records (projects, campaigns,
        // leads) together with their own lookup tables (pipeline/lead statuses).
        // A route-less parent with children renders as a collapsible group; it
        // is dropped automatically when the actor can see none of its children.
        [
            'key' => 'marketing-leads',
            'label' => 'navigation.marketingLeads',
            'icon' => 'megaphone',
            'route' => null,
            'permission' => null,
            'children' => [
                [
                    // Projects (spec 0023): operational record grouping a
                    // classification (status/business function/state/product
                    // category) and, optionally, its budget-constrained campaigns.
                    'key' => 'projects',
                    'label' => 'navigation.projects',
                    'icon' => 'layers',
                    'route' => '/projects',
                    'permission' => 'projects.view',
                ],
                [
                    // Campaigns (spec 0023): standalone or project-linked
                    // (read-through classification/budget, BR-2/BR-3).
                    'key' => 'campaigns',
                    'label' => 'navigation.campaigns',
                    'icon' => 'waypoints',
                    'route' => '/campaigns',
                    'permission' => 'campaigns.view',
                ],
                [
                    // Leads (spec 0024): a contact (Referent) generated by a
                    // Campaign, optionally scoped to a Sede/Fonte/Operatore.
                    // Navigable parent: clicking it opens the list (/leads); the
                    // dedicated import module hangs beneath it (user decision
                    // 2026-07-16).
                    'key' => 'leads',
                    'label' => 'navigation.leads',
                    'icon' => 'user-plus',
                    'route' => '/leads',
                    'permission' => 'leads.view',
                    'children' => [
                        [
                            // Import (spec 0034): the history table of every
                            // import run plus the multi-step wizard. Gated by the
                            // lead module's `leads.import` ability (the former
                            // dedicated `import-runs.*` set was a duplicate,
                            // removed 2026-07-17).
                            'key' => 'imports',
                            'label' => 'navigation.imports',
                            'icon' => 'file-up',
                            'route' => '/imports',
                            'permission' => 'leads.import',
                        ],
                    ],
                ],
                [
                    // Pipeline statuses (spec 0023): the Project/Campaign
                    // classification pick-list, delete-guarded (BR-4).
                    'key' => 'pipeline-statuses',
                    'label' => 'navigation.pipelineStatuses',
                    'icon' => 'tag',
                    'route' => '/pipeline-statuses',
                    'permission' => 'pipeline-statuses.view',
                ],
            ],
        ],

        // "Opportunita' e Commesse" (spec 0043, D-4): Opportunities (spec 0040,
        // a commercial deal against an Anagrafica, created manually or
        // generated from a Lead) gathered under one collapsible parent with
        // their own working-state pick-list (opportunity statuses). No
        // "Commesse" module exists yet in this iteration — only the group's
        // name anticipates it. A route-less parent with children renders as a
        // collapsible group; it is dropped automatically when the actor can
        // see none of its children.
        [
            'key' => 'opportunities-group',
            'label' => 'navigation.opportunitiesAndCommesse',
            'icon' => 'briefcase',
            'route' => null,
            'permission' => null,
            'children' => [
                [
                    'key' => 'opportunities',
                    'label' => 'navigation.opportunities',
                    'icon' => 'handshake',
                    'route' => '/opportunities',
                    'permission' => 'opportunities.view',
                ],
                [
                    // Opportunity statuses (spec 0043): the Opportunity
                    // working-state pick-list, delete-guarded (BR-2).
                    'key' => 'opportunity-statuses',
                    'label' => 'navigation.opportunityStatuses',
                    'icon' => 'tag',
                    'route' => '/opportunity-statuses',
                    'permission' => 'opportunity-statuses.view',
                ],
                [
                    // Opportunity workflow configurator (spec 0047): a NEW,
                    // separate "stato di lavorazione" dimension (distinct
                    // from the pipeline opportunity-statuses above),
                    // criteria-matched per Opportunity.
                    'key' => 'opportunity-workflows',
                    'label' => 'navigation.opportunityWorkflows',
                    'icon' => 'workflow',
                    'route' => '/opportunity-workflows',
                    'permission' => 'opportunity-workflows.viewAny',
                ],
                [
                    // Request Management (spec 0049): the operative
                    // "Gestione Richieste" view over Opportunities for
                    // commercial operators (D-1, no new entity). Gated by its
                    // OWN `request-management.*` permission set, never
                    // `opportunities.*`.
                    'key' => 'request-management',
                    'label' => 'navigation.requestManagement',
                    'icon' => 'clipboard-list',
                    'route' => '/request-management',
                    'permission' => 'request-management.view',
                ],
            ],
        ],

        // "Anagrafiche" domain: every registry/contact master-data record under
        // one collapsible parent. Replaces the former flat "Gestione" section,
        // dissolved into domain groups (user decision 2026-07-17). A route-less
        // parent renders collapsible; NavigationService drops it when the actor
        // can see none of its children. Ordered from the central registry outward.
        [
            'key' => 'registries-group',
            'label' => 'navigation.registries',
            'icon' => 'book-user',
            'route' => null,
            'permission' => null,
            'children' => [
                [
                    'key' => 'registries',
                    'label' => 'navigation.registries',
                    'icon' => 'book-user',
                    'route' => '/registries',
                    'permission' => 'registries.view',
                ],
                [
                    'key' => 'referents',
                    'label' => 'navigation.referents',
                    'icon' => 'contact-round',
                    'route' => '/referents',
                    'permission' => 'referents.view',
                ],
                [
                    // Referent types (spec 0016): the Referent classification
                    // pick-list. Moved here from Configurazione: it belongs to
                    // the registry domain it classifies (user decision 2026-07-17).
                    'key' => 'referent-types',
                    'label' => 'navigation.referentTypes',
                    'icon' => 'tags',
                    'route' => '/referent-types',
                    'permission' => 'referent-types.view',
                ],
                [
                    'key' => 'companies',
                    'label' => 'navigation.companies',
                    'icon' => 'building',
                    'route' => '/companies',
                    'permission' => 'companies.view',
                ],
                [
                    // Company Sites (spec 0020): flexible site
                    // anagraphic under a Company.
                    'key' => 'company-sites',
                    'label' => 'navigation.companySites',
                    'icon' => 'building-2',
                    'route' => '/company-sites',
                    'permission' => 'company-sites.view',
                ],
                [
                    'key' => 'operational-sites',
                    'label' => 'navigation.operationalSites',
                    'icon' => 'map-pin',
                    'route' => '/operational-sites',
                    'permission' => 'operational-sites.view',
                ],
            ],
        ],

        // "Prodotti" domain: the product catalogue plus its own lookup tables
        // (categories, attributes, VAT rates) under one collapsible parent
        // (user decision 2026-07-17). Same collapsible-group shape as above.
        [
            'key' => 'products-group',
            'label' => 'navigation.products',
            'icon' => 'package',
            'route' => null,
            'permission' => null,
            'children' => [
                [
                    'key' => 'products',
                    'label' => 'navigation.products',
                    'icon' => 'package',
                    'route' => '/products',
                    'permission' => 'products.view',
                ],
                [
                    'key' => 'product-categories',
                    'label' => 'navigation.productCategories',
                    'icon' => 'list-tree',
                    'route' => '/product-categories',
                    'permission' => 'product-categories.view',
                ],
                [
                    'key' => 'attributes',
                    'label' => 'navigation.attributes',
                    'icon' => 'sliders-horizontal',
                    'route' => '/attributes',
                    'permission' => 'attributes.view',
                ],
                [
                    'key' => 'vat-rates',
                    'label' => 'navigation.vatRates',
                    'icon' => 'percent',
                    'route' => '/vat-rates',
                    'permission' => 'vat-rates.view',
                ],
            ],
        ],

        // "Premi e Incentivi": the reward domain promoted to its own top-level
        // collapsible group (user decision 2026-07-24). Gathers the read-only
        // "Referenti con Buoni" aggregated view (spec 0059) and the "Buoni,
        // Premi e Incentivi" type catalogue (spec 0058) — previously scattered
        // under Anagrafiche and Configurazione respectively. Route-less parent:
        // renders collapsible, dropped when the actor can see no child.
        [
            'key' => 'rewards-group',
            'label' => 'navigation.rewards',
            'icon' => 'award',
            'route' => null,
            'permission' => null,
            'children' => [
                [
                    // Rewarded referents (spec 0059): the aggregated, READ-ONLY
                    // view (D-6) over Referenti holding at least one Reward.
                    // Gated by its OWN `rewarded-referents.*` set, never
                    // `referents.*` (precedent request-management).
                    'key' => 'rewarded-referents',
                    'label' => 'navigation.rewardedReferents',
                    'icon' => 'handshake',
                    'route' => '/rewarded-referents',
                    'permission' => 'rewarded-referents.view',
                ],
                [
                    // Reward types (spec 0058): the "Buoni, Premi e Incentivi"
                    // configuration pick-list — the type catalogue for the
                    // reward-assignment flows (D-1/D-7), not the assigned
                    // rewards themselves.
                    'key' => 'reward-types',
                    'label' => 'navigation.rewardTypes',
                    'icon' => 'gift',
                    'route' => '/reward-types',
                    'permission' => 'reward-types.view',
                ],
            ],
        ],

        // "Configurazione": cross-cutting lookup tables not tied to a single
        // domain. Product/registry pick-lists moved into their domain groups
        // above; custom fields moved to Amministrazione (user decision
        // 2026-07-17). What remains are the taxonomies shared across modules.
        [
            'key' => 'configuration',
            'label' => 'navigation.configuration',
            'icon' => null,
            'route' => null,
            'permission' => null,
            'type' => 'section',
            'children' => [
                [
                    'key' => 'business-functions',
                    'label' => 'navigation.businessFunctions',
                    'icon' => 'briefcase',
                    'route' => '/business-functions',
                    'permission' => 'business-functions.view',
                ],
                [
                    'key' => 'sectors',
                    'label' => 'navigation.sectors',
                    'icon' => 'list-tree',
                    'route' => '/sectors',
                    'permission' => 'sectors.view',
                ],
                [
                    'key' => 'tags',
                    'label' => 'navigation.tags',
                    'icon' => 'tag',
                    'route' => '/tags',
                    'permission' => 'tags.view',
                ],
                [
                    'key' => 'sources',
                    'label' => 'navigation.sources',
                    'icon' => 'waypoints',
                    'route' => '/sources',
                    'permission' => 'sources.view',
                ],
            ],
        ],

        // "Amministrazione": system-level access control, the dynamic-field
        // catalogue and data migration (who-can-do-what plus admin-only tooling,
        // kept apart from the reference-data configuration above). The section
        // is dropped automatically when the actor can see none of its children.
        [
            'key' => 'administration',
            'label' => 'navigation.administration',
            'icon' => null,
            'route' => null,
            'permission' => null,
            'type' => 'section',
            'children' => [
                [
                    'key' => 'users',
                    'label' => 'navigation.users',
                    'icon' => 'users',
                    'route' => '/users',
                    'permission' => 'users.view',
                ],
                [
                    'key' => 'roles',
                    'label' => 'navigation.roles',
                    'icon' => 'shield-check',
                    'route' => '/roles',
                    'permission' => 'roles.view',
                ],
                [
                    // Universal custom fields (spec 0021): the admin catalogue
                    // of dynamic fields grafted onto every custom-fieldable
                    // module. Moved here from Configurazione (user decision
                    // 2026-07-17): it is an admin-only tool, not a taxonomy.
                    'key' => 'custom-fields',
                    'label' => 'navigation.customFields',
                    'icon' => 'puzzle',
                    'route' => '/custom-fields',
                    'permission' => 'custom-fields.view',
                ],
                [
                    'key' => 'migrations',
                    // Namespaced i18n key: `migrations` strings live in their own
                    // i18next namespace (see frontend i18n/index.ts).
                    'label' => 'migrations:nav.label',
                    'icon' => 'database-zap',
                    'route' => '/migrations',
                    'permission' => null,
                    'role' => 'super-admin',
                ],
            ],
        ],
    ],

];
