<?php

namespace App\Models;

use App\Models\Abstracts\BaseModel;
use App\Models\Concerns\LogsModelActivity;
use Database\Factories\CampaignFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Campaign entity (spec 0023): optionally linked to a Project via
 * `project_id`. `partner_id` is ALWAYS the campaign's own.
 * `pipeline_status_id` is the DERIVED set (BR-2): forced NULL by the
 * service when linked to a project (its effective value is then read
 * through `project`), required when standalone. `code` (CMP-0001...) is
 * generated by the service inside the create transaction (BR-1) with a
 * pessimistic lock: deliberately NOT in #[Fillable].
 *
 * Spec 0094, D-1/D-2: the former single `business_function_id`/
 * `product_category_id` columns are likewise BR-2-derived, but no longer
 * scalar — REPLACED by `productLines()`, a one-to-many collection (see
 * CampaignProductLine) EMPTY when linked (the effective rows are read
 * through `project`), required (min 1) when standalone.
 *
 * `country_id`/`state_id`/`province_id`/`city_id` are NO LONGER part of BR-2
 * (spec 0027, D-3): they follow BR-5 instead — a REFINEMENT of the linked
 * project's geo. A level the project fills is NULL here (prohibited on
 * write) and read through `project`; a level the project leaves empty is the
 * campaign's own. CampaignResource always exposes the EFFECTIVE (merged)
 * geo, never these raw columns directly.
 */
#[Fillable([
    'project_id',
    'name',
    'description',
    'partner_id',
    'pipeline_status_id',
    'country_id',
    'state_id',
    'province_id',
    'city_id',
    'operational_site_id',
    'start_date',
    'end_date',
    'total_budget',
    'target_lead',
])]
class Campaign extends BaseModel
{
    /** @use HasFactory<CampaignFactory> */
    use HasFactory, LogsModelActivity;

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'start_date' => 'date',
            'end_date' => 'date',
            'total_budget' => 'decimal:2',
            'target_lead' => 'int',
        ];
    }

    /**
     * The linked project, if any (nullable, restrictOnDelete — BR-5).
     */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    /**
     * The Referent acting as the campaign's partner (D-1).
     */
    public function partner(): BelongsTo
    {
        return $this->belongsTo(Referent::class, 'partner_id');
    }

    /**
     * The campaign's OWN status assignment (BR-2) — NULL when linked to a
     * project, never the effective (own-or-derived) one, which is resolved
     * read-side by the service/resource.
     */
    public function pipelineStatus(): BelongsTo
    {
        return $this->belongsTo(PipelineStatus::class);
    }

    /**
     * The campaign's OWN country/state/province/city (BR-5) — NULL for
     * whichever level the linked project already fills; the EFFECTIVE
     * (merged) geo is resolved read-side by the service/resource.
     */
    public function country(): BelongsTo
    {
        return $this->belongsTo(Country::class);
    }

    public function state(): BelongsTo
    {
        return $this->belongsTo(State::class);
    }

    public function province(): BelongsTo
    {
        return $this->belongsTo(Province::class);
    }

    public function city(): BelongsTo
    {
        return $this->belongsTo(City::class);
    }

    /**
     * The "funzione aziendale" + "categoria prodotto" rows OWNED by this
     * campaign (spec 0094, D-1/D-2), SUBSTITUTING the former single
     * `business_function_id`/`product_category_id` columns — EMPTY when
     * linked to a project (BR-2): the campaign never carries its own rows in
     * that case, the EFFECTIVE ones are read through `project` instead (see
     * CampaignResource/CampaignsTableDefinition).
     *
     * @return HasMany<CampaignProductLine, $this>
     */
    public function productLines(): HasMany
    {
        return $this->hasMany(CampaignProductLine::class);
    }

    /**
     * The sede (spec 0047-style inheritance cascade project -> campaign ->
     * lead): a prefill-modifiable field, not a read-through — no server-side
     * inheritance/lock, the frontend only pre-fills the child form from it.
     */
    public function operationalSite(): BelongsTo
    {
        return $this->belongsTo(OperationalSite::class);
    }

    /**
     * The leads generated by this campaign (spec 0024, BR-2/D-4: restrict-on-
     * delete — CampaignService::delete() guards on this before deleting).
     *
     * @return HasMany<Lead, $this>
     */
    public function leads(): HasMany
    {
        return $this->hasMany(Lead::class);
    }
}
