<?php

namespace App\Models;

use App\Enums\LeadLifecycleStatus;
use App\Models\Abstracts\BaseModel;
use App\Models\Concerns\LogsModelActivity;
use Database\Factories\LeadFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

/**
 * Lead entity (spec 0024): a contact generated by a campaign. `registry_id`/
 * `campaign_id` are mandatory (BR-1, spec 0041 D-1: the contact is an
 * Anagrafica, not a Referent);
 * `operational_site_id`/`source_id`/`operator_id`/`notes` are optional. No
 * `code` (D-3): unlike Project/Campaign, a Lead carries no sequential
 * identifier. `extra_fields` (spec 0033) is a raw JSON key/value store for
 * free-form data — typed manually on the Lead form or mapped to `__extra__`
 * during the import wizard — deliberately NOT the Universal Custom Fields
 * system (spec 0021).
 */
#[Fillable([
    'registry_id',
    'campaign_id',
    'operational_site_id',
    'source_id',
    'operator_id',
    'notes',
    'extra_fields',
    'state_id',
])]
class Lead extends BaseModel
{
    /** @use HasFactory<LeadFactory> */
    use HasFactory, LogsModelActivity;

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'extra_fields' => 'array',
        ];
    }

    public function registry(): BelongsTo
    {
        return $this->belongsTo(Registry::class);
    }

    public function campaign(): BelongsTo
    {
        return $this->belongsTo(Campaign::class);
    }

    public function operationalSite(): BelongsTo
    {
        return $this->belongsTo(OperationalSite::class);
    }

    public function source(): BelongsTo
    {
        return $this->belongsTo(Source::class);
    }

    /**
     * The Regione (spec 0047, D1): derived server-side from the sede
     * (`operationalSite->stateId`) at create/update time — never
     * user-editable directly.
     */
    public function state(): BelongsTo
    {
        return $this->belongsTo(State::class, 'state_id');
    }

    /**
     * The internal user assigned to work this lead.
     */
    public function operator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'operator_id');
    }

    /**
     * The opportunity generated from this lead, if any (spec 0040, D-2: at
     * most one — `opportunities.lead_id` is UNIQUE). The lead itself is never
     * modified when one exists (spec 0040 D-5: no `is_converted` flag).
     */
    public function opportunity(): HasOne
    {
        return $this->hasOne(Opportunity::class);
    }

    public function lifecycleStatus(): LeadLifecycleStatus
    {
        return LeadLifecycleStatus::forLead($this);
    }

    /**
     * The products the contact recorded interest in (spec 0094, D-5): a
     * plain reference collection, no pivot payload — mirrors
     * Opportunity::productsOfInterest(). Written exclusively by
     * App\Services\Leads\LeadProductInterestWriter, which also guarantees
     * every selected product's category is covered by the lead's Campaign's
     * EFFECTIVE product lines.
     *
     * @return BelongsToMany<Product, $this>
     */
    public function productsOfInterest(): BelongsToMany
    {
        return $this->belongsToMany(Product::class, 'lead_product')->orderBy('products.name');
    }
}
