<?php

namespace App\Models;

use App\Models\Abstracts\BaseModel;
use App\Models\Concerns\LogsModelActivity;
use Database\Factories\ProjectFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;

/**
 * Project entity (spec 0023): may stand alone or own Campaigns, which then
 * read its status/business-function/region/product-category read-through
 * (BR-2) instead of carrying their own. `code` (PRJ-0001...) is generated by
 * the service inside the create transaction (BR-1) with a pessimistic lock:
 * deliberately NOT in #[Fillable] so store/update input can never set it.
 * `total_budget`/`target_lead` mirror the Product decimal(15,2)/unsigned int
 * convention. Lowering `total_budget` below the sum already allocated to its
 * campaigns is allowed (D-4) — see ProjectResource for the computed
 * `allocated_budget`/`remaining_budget` exposed read-side.
 *
 * Spec 0094, D-1/D-2: the former single `business_function_id`/
 * `product_category_id` columns are REPLACED by `productLines()`, a
 * one-to-many collection (see ProjectProductLine), mirroring the Opportunity's
 * own amendment rev.3 collection.
 */
#[Fillable([
    'name',
    'description',
    'pipeline_status_id',
    'country_id',
    'state_id',
    'province_id',
    'city_id',
    'partner_id',
    'operational_site_id',
    'start_date',
    'end_date',
    'total_budget',
    'target_lead',
])]
class Project extends BaseModel
{
    /** @use HasFactory<ProjectFactory> */
    use HasFactory, LogsModelActivity;

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'start_date' => 'date',
            'end_date' => 'date',
            'total_budget' => 'decimal:2',
            'target_lead' => 'int',
        ];
    }

    public function pipelineStatus(): BelongsTo
    {
        return $this->belongsTo(PipelineStatus::class);
    }

    public function country(): BelongsTo
    {
        return $this->belongsTo(Country::class);
    }

    public function state(): BelongsTo
    {
        return $this->belongsTo(State::class);
    }

    public function province(): BelongsTo
    {
        return $this->belongsTo(Province::class);
    }

    public function city(): BelongsTo
    {
        return $this->belongsTo(City::class);
    }

    /**
     * The "funzione aziendale" + "categoria prodotto" rows (spec 0094,
     * D-1/D-2), SUBSTITUTING the former single `business_function_id`/
     * `product_category_id` columns.
     *
     * @return HasMany<ProjectProductLine, $this>
     */
    public function productLines(): HasMany
    {
        return $this->hasMany(ProjectProductLine::class);
    }

    /**
     * The Referent acting as the project's partner (D-1: "Partner" points to
     * `referents`).
     */
    public function partner(): BelongsTo
    {
        return $this->belongsTo(Referent::class, 'partner_id');
    }

    /**
     * The sede (spec 0047-style inheritance cascade project -> campaign ->
     * lead): a prefill-modifiable field, not a read-through — no server-side
     * inheritance/lock, the frontend only pre-fills the child form from it.
     */
    public function operationalSite(): BelongsTo
    {
        return $this->belongsTo(OperationalSite::class);
    }

    /**
     * The campaigns linked to this project (`campaigns.project_id`,
     * restrictOnDelete — BR-5: a project with campaigns cannot be deleted).
     */
    public function campaigns(): HasMany
    {
        return $this->hasMany(Campaign::class);
    }

    /**
     * The leads reachable through this project's campaigns (spec 0026, D-4:
     * no direct FK — a Project has no own leads, only through Campaign).
     *
     * @return HasManyThrough<Lead, Campaign, $this>
     */
    public function leads(): HasManyThrough
    {
        return $this->hasManyThrough(Lead::class, Campaign::class);
    }
}
