import type { HelpGuide } from '../../types'

const guide: HelpGuide = {
  key: 'leads',
  title: 'Leads',
  summary: 'A lead is a contact generated by a campaign, always linked to a registry and to a campaign.',
  sections: [
    {
      id: 'create-a-lead',
      title: 'Creating a lead',
      blocks: [
        {
          type: 'steps',
          items: ['Open **Marketing & Leads › Leads** and click **New lead**.', 'Fill in the fields (see table).', 'Click **Save**.'],
        },
        {
          type: 'table',
          headers: ['Field', 'Notes'],
          rows: [
            ['**Registry**', 'Required: an already existing registry.'],
            ['**Campaign**', 'Required.'],
            ['**Site**', "The lead's operational site."],
            ['**Operator**', 'Who follows the lead; the list shows only the operators of the chosen site.'],
            ['**Source**', 'The channel the lead came from.'],
            ['Products of interest', "Limited to the campaign's categories."],
            ['**Notes**', 'Free-form text, up to 5000 characters.'],
            ['Extra fields / Imported data', '**Key** and **Value** pairs, usually from an import.'],
          ],
        },
        {
          type: 'paragraph',
          text: 'If you change the campaign and some products are no longer covered, QNet asks for confirmation: click **Remove and continue**.',
        },
        {
          type: 'tip',
          text: 'Turn on **Automatically convert to Opportunity** to create the opportunity together with the lead right away (requires the permission to create opportunities).',
        },
      ],
    },
    {
      id: 'lead-status',
      title: 'Lead status',
      blocks: [
        { type: 'paragraph', text: 'The **Lead status** updates itself:' },
        {
          type: 'table',
          headers: ['Lead status', 'When'],
          rows: [
            ['**Unassigned**', 'The lead has no operator yet.'],
            ['**Assigned**', 'The lead has an operator assigned.'],
            ['**Converted to opportunity**', 'An opportunity was created from the lead.'],
          ],
        },
        {
          type: 'paragraph',
          text: 'The **Assigned** and **Converted** columns let you filter leads by status.',
        },
      ],
    },
    {
      id: 'assign-operators',
      title: 'Assigning leads to operators',
      blocks: [
        {
          type: 'steps',
          items: [
            'In the **Leads** table, select the leads.',
            'Click **Assign operators** and choose the **Site**.',
            'Choose the **Assignment type**: **Balanced split** (distributes leads balancing the workload) or **Assign to operator** (all to the same operator).',
            'Click **Assign**.',
          ],
        },
        {
          type: 'paragraph',
          text: "Only the site's operators competent for the chosen leads are shown; leads with no competent operator are flagged as excluded.",
        },
        {
          type: 'warning',
          text: 'Some assignment types are unavailable if the selection contains leads from different campaigns.',
        },
      ],
    },
    {
      id: 'convert-to-opportunity',
      title: 'Converting a lead to an opportunity',
      blocks: [
        { type: 'paragraph', text: 'Three ways, no forms to fill in:' },
        {
          type: 'list',
          items: [
            "from the lead record, with **Create opportunity** (the button then becomes **Go to opportunity**);",
            'from the table, selecting several leads and clicking **Convert to opportunities**;',
            'at the end of an import, with the automatic conversion.',
          ],
        },
        {
          type: 'table',
          headers: ['In the opportunity', 'Where it comes from'],
          rows: [
            ['Registry, Source, General notes', 'From the lead.'],
            ['Operational site', "The lead's site, editable."],
            ['Account managers', "The lead's operator becomes the second account manager."],
            ['Classification rows', "The campaign's (or its project's) business functions and categories."],
            ['Products of interest', "The lead's own."],
          ],
        },
        {
          type: 'paragraph',
          text: 'A linked quote is created together with the opportunity, with one row for each sellable product of interest (quantity 1, product price).',
        },
        {
          type: 'paragraph',
          text: "Conversion is blocked if the lead already has an opportunity, if the campaign has no business function or product category, or if the registry already has an open opportunity (in that case, add the quote to the existing one).",
        },
        {
          type: 'warning',
          text: 'Bulk conversion is all-or-nothing. If a single lead cannot be converted, QNet lists the blocked ones and why: deselect them and try again.',
        },
      ],
    },
  ],
}

export default guide
