/**
 * The help guide keys of every navigable module (spec 0143 context: the 49
 * navigation keys of the first release, plus the always-visible `general`
 * guide) — extended per spec as new modules ship (spec 0175: `email-templates`,
 * `document-bundles`). A new navigable module needs both a new entry here and
 * its `content/{it,en}/<key>.ts` pair (parity test enforces the latter).
 */
export const GENERAL_HELP_KEY = 'general'

export const HELP_GUIDE_KEYS: readonly string[] = [
  GENERAL_HELP_KEY,
  'dashboard',
  'notifications',
  'projects',
  'campaigns',
  'leads',
  'imports',
  'pipeline-statuses',
  'opportunities',
  'quote-workflows',
  'quotes',
  'work-orders',
  'email-templates',
  'document-bundles',
  'contract-statuses',
  'contracts',
  'request-management',
  'field-change-requests',
  'enrollee-management',
  'tasks',
  'task-statuses',
  'task-types',
  'task-categories',
  'task-priorities',
  'task-importances',
  'task-templates',
  'time-entries',
  'registries',
  'referents',
  'referent-types',
  'companies',
  'company-sites',
  'operational-sites',
  'products',
  'product-categories',
  'attributes',
  'vat-rates',
  'units-of-measure',
  'product-typologies',
  'rewarded-referents',
  'reward-types',
  'reward-statuses',
  'business-functions',
  'sectors',
  'tags',
  'sources',
  'commission-configurations',
  'payment-methods',
  'document-layouts',
  'users',
  'roles',
  'custom-fields',
  'migrations',
]
