/**
 * Task templates domain (spec 0124). Split into a sibling file to keep
 * `en.ts` within the size limits (see `.claude/rules/engineering.md` §6). A
 * template is a header plus ordered rows (D-1): whoever creates a Commessa
 * can pick an active one to generate the corresponding tasks, as independent
 * copies (D-6).
 */

export const taskTemplates = {
  title: 'Task Templates',
  subtitle: 'Configure the templates used to generate a Commessa’s tasks.',
  forbidden: 'You do not have permission to view task templates.',
  columns: {
    name: 'Name',
    description: 'Description',
    items_count: 'Rows',
    is_active: 'Active',
    created_at: 'Created at',
    updated_at: 'Updated at',
  },
  detail: {
    title: 'Task template detail',
    subtitle: 'Read-only view of the selected task template.',
    loadError: 'Unable to load the task template. Please retry.',
    description: 'Description',
    isActive: 'Active',
    itemsCount: '{{count}} rows',
    created_at: 'Created at',
    updated_at: 'Updated at',
    items: {
      title: 'Rows',
      dueOffsetDays: 'Due: +{{count}} days',
      estimatedMinutes: 'Estimate: {{value}} min',
    },
  },
  form: {
    newTaskTemplate: 'New task template',
    createTitle: 'Create task template',
    createSubtitle: 'Add a new task template.',
    editTitle: 'Edit task template',
    editSubtitle: 'Update the selected task template.',
    name: 'Name',
    description: 'Description',
    isActive: 'Active',
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    created: 'Task template created successfully.',
    updated: 'Task template updated successfully.',
    deleted: 'Task template deleted successfully.',
    nameRequired: 'Name is required.',
    nameMax: 'Name may contain at most 191 characters.',
    genericError: 'Something went wrong. Please retry.',
    deleteError: 'Unable to delete the task template. Please retry.',
    deleteForbidden: 'You cannot delete this task template.',
    deleteInUse: 'This task template was used to generate Commesse and cannot be deleted. Deactivate it instead.',
    sections: {
      identity: {
        title: 'Details',
        description: 'Name, description and status.',
      },
      items: {
        title: 'Rows',
        description: 'Tasks generated by the template, in order.',
      },
      stages: {
        title: 'Phases',
        description: 'Group the rows into phases, drag rows between them.',
      },
    },
    /** Spec 0146 D-2: phases group the template's rows; copied into the commessa's own `work_order_stages` at generation. */
    stages: {
      add: 'Add phase',
      namePlaceholder: 'Phase name…',
      remove: 'Remove phase',
      dragHandleLabel: 'Reorder phase',
      noStage: 'No phase',
      empty: 'No phase yet.',
    },
    items: {
      add: 'Add row',
      remove: 'Remove row',
      dragHandleLabel: 'Reorder row',
      title: 'Title',
      description: 'Description',
      descriptionPlaceholder: 'Optional description…',
      estimatedMinutes: 'Estimated time (min)',
      dueOffsetDays: 'Due (days from Commessa start)',
      status: 'Initial status',
      statusPlaceholder: 'No status',
      statusSearchPlaceholder: 'Search status…',
      statusEmpty: 'No status available.',
      statusError: 'Unable to load statuses.',
      statusClear: 'Clear selected status',
      attachments: 'Attachments',
      attachmentsAdd: 'Add attachment',
      attachmentsRemove: 'Remove attachment',
      attachmentsUploadFailed: 'Upload failed for: {{files}}.',
      required: 'Add at least one row.',
      tooMany: 'You can add at most {{max}} rows.',
      titleRequired: 'Title is required.',
      titleMax: 'Title may contain at most 191 characters.',
      dueOffsetInvalid: 'Due must be a number of days between 0 and {{max}}.',
      estimatedMinutesInvalid: 'The estimated time is not valid.',
      hasErrors: 'Fix the highlighted rows before saving.',
    },
  },
}
