<?php

declare(strict_types=1);

namespace App\Support\Notifications;

use App\Enums\AssignmentTargetEnum;
use App\Models\User;

/**
 * Resolves the SPA path a notification should point THIS recipient to
 * (spec 0081, decisione utente 2026-08-04). Per-recipient rather than
 * per-record because an Opportunity is reachable through two different
 * modules gated by two different permission sets (spec 0049, D-1): the same
 * transfer notifies people who may open it from `/opportunities` and people
 * who may only open it from `/request-management`.
 *
 * Returns a PATH or null, never an absolute URL — the contract every
 * notification of this repo already honours (see
 * RequestTransferredNotification::dataActionUrl()): `config('app.frontend_url')`
 * is prepended in the mail CTA and nowhere else, so a stored `action_url`
 * stays valid if the frontend ever moves.
 *
 * Null means "this recipient may not open the record from any module": the
 * caller then omits the mail button and appends the request-access sentence,
 * rather than handing out a link that lands on a 403. The bell already
 * renders a null `action_url` as a non-clickable row (notification-item.tsx),
 * so no frontend change is needed for that case.
 *
 * Static because it is pure logic over the recipient's abilities with no
 * state and no dependencies — the role `OperationalSiteLabel` and
 * `MentionParser` already play in this codebase.
 */
final class RecordLinkResolver
{
    /**
     * @param  int  $recordId  the Opportunity id, for `/opportunities/:id`
     * @param  ?int  $requestManagementRecordId  spec 0086, MT-04b: the
     *                                           request-management fallback
     *                                           now opens a Quote (a grid row
     *                                           IS an Offerta, not the
     *                                           Opportunity any more), so its
     *                                           id can DIVERGE from
     *                                           $recordId. Null (every caller
     *                                           predating spec 0086) falls
     *                                           back to $recordId — the two
     *                                           ids were the same record
     *                                           before this spec, so nothing
     *                                           changes for them.
     */
    public static function pathFor(User $notifiable, AssignmentTargetEnum $target, int $recordId, ?int $requestManagementRecordId = null): ?string
    {
        return match ($target) {
            AssignmentTargetEnum::Registry => $notifiable->can('registries.view')
                ? "/registries/{$recordId}"
                : null,
            AssignmentTargetEnum::Opportunity => self::opportunityPath($notifiable, $recordId, $requestManagementRecordId ?? $recordId),
        };
    }

    /**
     * The opportunities module wins when the recipient may see it, request
     * management is the fallback (decisione utente): both routes exist in the
     * SPA — `/opportunities/:id` is generated by `buildModuleRoutes()` from
     * the module registry, `/request-management/:id` is declared by hand.
     */
    private static function opportunityPath(User $notifiable, int $recordId, int $requestManagementRecordId): ?string
    {
        if ($notifiable->can('opportunities.view')) {
            return "/opportunities/{$recordId}";
        }

        if ($notifiable->can('request-management.view')) {
            return "/request-management/{$requestManagementRecordId}";
        }

        return null;
    }
}
