<?php

namespace App\Services\ApiDocs;

use Dedoc\Scramble\Generator;
use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Route as RouteFacade;
use Symfony\Component\Finder\Finder;

/**
 * The OpenAPI document of the /api endpoints, generated by Scramble from the live
 * routes, FormRequests and Resources (specs 0209, 0210): never hand-written.
 *
 * The cache key embeds a signature of the sources the document is derived from,
 * so adding, editing or removing a route, controller, request or resource yields
 * a new key and a regenerated document without any manual invalidation. Only
 * file paths and mtimes are read, never contents.
 */
class OpenApiDocumentProvider
{
    public const string CACHE_KEY_PREFIX = 'api-docs.openapi.';

    private const array SOURCE_FILES = [
        'routes/api.php',
        'config/scramble.php',
        'config/external-api.php',
    ];

    private const array SOURCE_DIRECTORIES = [
        'routes/api',
        'app/Http/Controllers',
        'app/Http/Requests',
        'app/Http/Resources',
        'app/Services/ApiDocs',
    ];

    /**
     * @return array<string, mixed>
     */
    public function document(): array
    {
        return Cache::remember(
            self::CACHE_KEY_PREFIX.$this->signature(),
            (int) config('external-api.docs.cache_ttl'),
            fn (): array => app(Generator::class)(),
        );
    }

    /**
     * Hash of every input of the document: source files (path + mtime) and the
     * routes registered under the API prefix (method + uri), so routes added at
     * runtime (not backed by a file) change the key as well.
     */
    public function signature(): string
    {
        return sha1(json_encode([$this->sourceFilesSignature(), $this->routesSignature()], JSON_THROW_ON_ERROR));
    }

    /**
     * @return array<int, string>
     */
    private function sourceFilesSignature(): array
    {
        $paths = array_map(base_path(...), self::SOURCE_FILES);

        foreach (self::SOURCE_DIRECTORIES as $directory) {
            foreach (Finder::create()->files()->in(base_path($directory))->name('*.php') as $file) {
                $paths[] = $file->getPathname();
            }
        }

        sort($paths);

        return array_map(static fn (string $path): string => $path.'@'.(is_file($path) ? filemtime($path) : 'missing'), $paths);
    }

    /**
     * @return array<int, string>
     */
    private function routesSignature(): array
    {
        $prefix = trim((string) config('external-api.prefix'), '/');

        return collect(RouteFacade::getRoutes()->getRoutes())
            ->filter(static fn (Route $route): bool => $route->uri() === $prefix || str_starts_with($route->uri(), $prefix.'/'))
            ->map(static fn (Route $route): string => implode('|', $route->methods()).' '.$route->uri().' '.$route->getActionName())
            ->sort()
            ->values()
            ->all();
    }
}
