<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Lead entity (spec 0024): a contact generated by a campaign. Ties an
 * Anagrafica (`registries`, spec 0041 D-1 — the contact, corrected from the
 * original Referent) to a Campaign, optionally to an OperationalSite, a
 * Source and an Operator (User), plus free-text notes. No `code` (D-3): a
 * Lead has none of Project/Campaign's sequential identifier.
 *
 * BR-2/D-4: cancellation is BLOCKING on every one of the 5 owner relations —
 * `restrictOnDelete()` on all of them, mirrored at the app layer by a
 * `abort(409, ...)` guard in each referenced module's Service (see
 * CampaignService/RegistryService/OperationalSiteService/SourceService/
 * UserService). Without the app-layer guard, the DB-level restrict would
 * surface as a raw QueryException (500), not a clean 409.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('leads', function (Blueprint $table) {
            $table->id();
            $table->foreignId('registry_id')->constrained('registries')->restrictOnDelete();
            $table->foreignId('campaign_id')->constrained('campaigns')->restrictOnDelete();
            $table->foreignId('operational_site_id')->nullable()->constrained('operational_sites')->restrictOnDelete();

            // Regione (spec 0047, D1): derived server-side from the lead's sede
            // at create/update time, never user-editable — hence nullable and
            // nullOnDelete, unlike the blocking relations above.
            $table->foreignId('state_id')->nullable()->constrained('states')->nullOnDelete();

            $table->foreignId('source_id')->nullable()->constrained('sources')->restrictOnDelete();
            $table->foreignId('operator_id')->nullable()->constrained('users')->restrictOnDelete();
            $table->text('notes')->nullable();

            // Campi Extra (spec 0033): a raw JSON key/value store for columns
            // that map to no declared field, whether typed on the form or mapped
            // to `__extra__` during the import wizard. Deliberately NOT the
            // Universal Custom Fields system (spec 0021) — free-form pairs only.
            $table->json('extra_fields')->nullable();

            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('leads');
    }
};
