<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Campaign entity (spec 0023): optionally linked to a Project via
 * `project_id` (nullable, `restrictOnDelete` — BR-5 defense in depth: a
 * project with campaigns cannot be deleted at the app layer, mirrored here at
 * the schema layer). `code` (CMP-0001...) is generated by the service inside
 * the create transaction (BR-1): NOT in the model's #[Fillable].
 *
 * `partner_id` and the geo/sede columns are ALWAYS the campaign's own
 * (pre-filled from the project by the frontend, but independently editable
 * and stored). `pipeline_status_id`/`business_function_id`/`state_id`/
 * `product_category_id` are the DERIVED set (BR-2): forced NULL by the
 * service when `project_id` is set (their effective value is read from the
 * linked project), and required by the service when `project_id` is null —
 * hence nullable here at the schema level regardless, the NOT NULL business
 * rule is enforced in the write pipeline, not the DB, since it is conditional
 * on `project_id`.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('campaigns', function (Blueprint $table) {
            $table->id();
            $table->string('code', 32)->unique();
            $table->foreignId('project_id')->nullable()->constrained('projects')->restrictOnDelete();
            $table->string('name', 191);
            $table->text('description')->nullable();
            $table->foreignId('partner_id')->nullable()->constrained('referents')->nullOnDelete();

            // Geographic scope cascade (spec 0027), mirroring `projects`: the
            // full Country -> State -> Province -> City chain, nullable +
            // nullOnDelete.
            $table->foreignId('country_id')->nullable()->constrained('countries')->nullOnDelete();
            $table->foreignId('state_id')->nullable()->constrained('states')->nullOnDelete();
            $table->foreignId('province_id')->nullable()->constrained('provinces')->nullOnDelete();
            $table->foreignId('city_id')->nullable()->constrained('cities')->nullOnDelete();

            // Sede: a PREFILL MODIFIABLE relation, pre-filled from the project
            // but independently editable and stored.
            $table->foreignId('operational_site_id')->nullable()->constrained('operational_sites')->nullOnDelete();

            $table->foreignId('pipeline_status_id')->nullable()->constrained('pipeline_statuses')->restrictOnDelete();
            $table->foreignId('business_function_id')->nullable()->constrained('business_functions')->nullOnDelete();
            $table->foreignId('product_category_id')->nullable()->constrained('product_categories')->nullOnDelete();
            $table->date('start_date')->nullable();
            $table->date('end_date')->nullable();
            $table->decimal('total_budget', 15, 2)->nullable();
            $table->unsignedInteger('target_lead')->nullable();
            $table->timestamps();

            $table->index('project_id');
            $table->index('country_id');
            $table->index('city_id');
            $table->index('operational_site_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('campaigns');
    }
};
