<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Project entity (spec 0023): may stand alone or own Campaigns (which then
 * inherit its status/business-function/region/product-category — see
 * `campaigns` migration). `code` (PRJ-0001...) is generated by the service
 * inside the create transaction (BR-1): NOT in the model's #[Fillable].
 * `pipeline_status_id` is required and `restrictOnDelete` (BR-4). Every other
 * classification FK is optional and `nullOnDelete` (losing the referenced row
 * just clears the field, it never cascades a delete of the project).
 * `total_budget` mirrors the Product decimal(15,2) convention; lowering it
 * below the sum already allocated to its campaigns is allowed (D-4) — the
 * check only ever flows the other way, from campaign to project (BR-3).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('projects', function (Blueprint $table) {
            $table->id();
            $table->string('code', 32)->unique();
            $table->string('name', 191);
            $table->text('description')->nullable();
            $table->foreignId('pipeline_status_id')->constrained('pipeline_statuses')->restrictOnDelete();
            $table->foreignId('business_function_id')->nullable()->constrained('business_functions')->nullOnDelete();

            // Geographic scope cascade (spec 0027): the full Country -> State ->
            // Province -> City chain used by the address module, same nullable +
            // nullOnDelete convention. The "country is required" rule (D-4) is a
            // FormRequest concern, never a DB constraint.
            $table->foreignId('country_id')->nullable()->constrained('countries')->nullOnDelete();
            $table->foreignId('state_id')->nullable()->constrained('states')->nullOnDelete();
            $table->foreignId('province_id')->nullable()->constrained('provinces')->nullOnDelete();
            $table->foreignId('city_id')->nullable()->constrained('cities')->nullOnDelete();

            // Sede: a PREFILL MODIFIABLE relation down the project -> campaign ->
            // lead chain, not a read-through — each level stores its own value.
            $table->foreignId('operational_site_id')->nullable()->constrained('operational_sites')->nullOnDelete();

            $table->foreignId('product_category_id')->nullable()->constrained('product_categories')->nullOnDelete();
            $table->foreignId('partner_id')->nullable()->constrained('referents')->nullOnDelete();
            $table->date('start_date')->nullable();
            $table->date('end_date')->nullable();
            $table->decimal('total_budget', 15, 2)->nullable();
            $table->unsignedInteger('target_lead')->nullable();
            $table->timestamps();

            $table->index('pipeline_status_id');
            $table->index('country_id');
            $table->index('city_id');
            $table->index('operational_site_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('projects');
    }
};
