<?php

namespace Database\Seeders;

use App\DataObjects\Projects\CreateProjectData;
use App\Models\Campaign;
use App\Models\PipelineStatus;
use App\Models\ProductCategory;
use App\Models\Project;
use App\Models\Referent;
use App\Models\State;
use App\Services\ProjectService;
use Database\Seeders\Concerns\ResolvesCategoryBusinessFunction;
use Database\Seeders\Concerns\SeedsItalianGeo;
use Faker\Factory as FakerFactory;
use Faker\Generator;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;

/**
 * Development seed for the projects module (spec 0023).
 *
 * Every project is created through ProjectService::create() — the same path
 * POST /api/projects uses — so the BR-1 sequential `code` (PRJ-0001...) is
 * generated by the real locked mechanism rather than reproduced here.
 * Classification FKs are drawn round-robin from the lookups seeded earlier
 * in DemoDataSeeder (business-functions/product-categories
 * seeded via their own Demo*Seeder, states via `locations:add`, partner via
 * DemoReferentSeeder), degrading gracefully to null when a lookup produced no
 * rows. The geo columns are scoped to Italy (regions/provinces/cities): this
 * gestionale's demo data is Italian-flavoured (it_IT faker across the other
 * seeders).
 *
 * Depends on DemoPipelineStatusSeeder, DemoBusinessFunctionSeeder and
 * DemoReferentSeeder — must run after all of them. Product categories are NOT
 * part of the demo dataset (they are client reference data, seeded by
 * QualificaCatalogSeeder): with none present the classification degrades to
 * null, like every other optional lookup. Idempotent: existing campaigns and projects
 * are cleared first (campaigns before projects — `campaigns.project_id` is
 * `restrictOnDelete`, BR-5 — so a stale campaign would block the project
 * delete on a second run); DemoCampaignSeeder recreates the campaigns right
 * after this seeder runs.
 *
 * Geo (spec 0027, BR-4): `SeedsItalianGeo::geoTuple()` cycles every project
 * through the four scope depths — country only / +region / +province /
 * +city — so all four `geo_scope` values are visible in the demo data
 * (AC-003), each tuple built from REAL rows read back from the `states`/
 * `provinces`/`cities` tables seeded by `locations:add`.
 */
class DemoProjectSeeder extends Seeder
{
    use ResolvesCategoryBusinessFunction;
    use SeedsItalianGeo;

    private const int PROJECTS = 14;

    public function __construct(private readonly ProjectService $projects) {}

    public function run(): void
    {
        // Children first (restrictOnDelete guard, BR-5): a stale campaign from
        // a previous run would otherwise block deleting its project below.
        // DemoCampaignSeeder repopulates campaigns right after this seeder.
        Campaign::query()->delete();
        Project::query()->delete();

        $faker = FakerFactory::create('it_IT');
        $faker->seed(20260713);

        $statuses = PipelineStatus::query()->orderBy('sort_order')->get();
        $productCategories = ProductCategory::query()->orderBy('name')->get();
        $partners = Referent::query()->orderBy('name')->get();
        $states = $this->italianStates();

        // The business function is DERIVED from each category's effective one
        // (spec 0023 REV), so every seeded project carries a coherent pair.
        $classificationPairs = $this->coherentClassificationPairs($productCategories);

        if ($statuses->isEmpty()) {
            // No status to satisfy the NOT NULL pipeline_status_id (BR-4/D-5):
            // nothing sensible to seed without it.
            return;
        }

        for ($index = 0; $index < self::PROJECTS; $index++) {
            $this->seedProject($faker, $index, $statuses, $states, $classificationPairs, $partners);
        }
    }

    /**
     * @param  Collection<int, PipelineStatus>  $statuses
     * @param  Collection<int, State>  $states
     * @param  Collection<int, array{product_category_id: int, business_function_id: int}>  $classificationPairs
     * @param  Collection<int, Referent>  $partners
     */
    private function seedProject(
        Generator $faker,
        int $index,
        Collection $statuses,
        Collection $states,
        Collection $classificationPairs,
        Collection $partners,
    ): void {
        // Every 5th project has no budget cap at all (A-1): campaigns linked
        // to it are never constrained by BR-3.
        $hasBudgetCap = $index % 5 !== 0;
        $startDate = $faker->dateTimeBetween('-18 months', '+1 month');
        $endDate = $faker->boolean(70)
            ? (clone $startDate)->modify('+'.$faker->numberBetween(2, 14).' months')
            : null;

        // Offset by 1 so the geo-depth cycle (mod 4) does NOT land on the same
        // indices as DemoCampaignSeeder::linkedCampaignCount()'s "0 campaigns
        // on every 4th project" rule (also mod 4, unoffset): without this,
        // every country-only-scope project would coincidentally be exactly
        // the one with zero linked campaigns, so BR-5's central case (a
        // campaign refining a country-only project down to region/city) would
        // never appear in the demo data.
        $geo = $this->geoTuple($states, $index + 1);

        $pair = $classificationPairs->isNotEmpty()
            ? $classificationPairs[$index % $classificationPairs->count()]
            : null;

        $data = new CreateProjectData(
            code: null,
            name: $faker->unique()->catchPhrase(),
            pipelineStatusId: $statuses[$index % $statuses->count()]->id,
            description: $faker->boolean(60) ? $faker->paragraph() : null,
            businessFunctionId: $pair['business_function_id'] ?? null,
            stateId: $geo['state_id'],
            productCategoryId: $pair['product_category_id'] ?? null,
            partnerId: $this->pick($partners, $index)?->id,
            operationalSiteId: null,
            startDate: $startDate->format('Y-m-d'),
            endDate: $endDate?->format('Y-m-d'),
            totalBudget: $hasBudgetCap ? $faker->randomFloat(2, 5000, 250000) : null,
            targetLead: $faker->boolean(80) ? $faker->numberBetween(5, 300) : null,
            countryId: $geo['country_id'],
            provinceId: $geo['province_id'],
            cityId: $geo['city_id'],
        );

        $this->projects->create($data);
    }

    /**
     * @template TModel of \Illuminate\Database\Eloquent\Model
     *
     * @param  Collection<int, TModel>  $items
     * @return TModel|null
     */
    private function pick(Collection $items, int $index): mixed
    {
        return $items->isNotEmpty() ? $items[$index % $items->count()] : null;
    }
}
