<?php

namespace Database\Seeders\QualificaCatalog;

/**
 * The client's staff outside the operator roster, transcribed from
 * "utenti_nome_cognome.csv" (user directive 2026-09-24). Pure data, read by
 * QualificaStaffSeeder, which creates each account with the base role
 * (Task and Segnatempo only).
 *
 * The CSV lists the WHOLE staff: the 68 accounts it shares with
 * OperatorRoster and TestUsersSeeder are left out here, so this list never
 * competes with the mansionario over a role. Names and accents as in the
 * CSV (re-encoded from ISO-8859-1), emails lowercased.
 */
final class StaffRoster
{
    /**
     * first name, last name, email.
     *
     * @var array<int, array{0: string, 1: string, 2: string}>
     */
    public const array USERS = [
        ['Giuseppe', 'Agus', 'giuseppe.agus@qualificagroup.com'],
        ['Laura', 'Allegretta', 'laura.allegretta@qualificagroup.com'],
        ['Silvia', 'Amoruso', 'silvia.amoruso@qualificagroup.com'],
        ['Roberta', 'Apperti', 'roberta.apperti@qualificagroup.com'],
        ['Andrea', 'Arena', 'andrea.arena@qualificagroup.com'],
        ['Emanuele', 'Ascione', 'emanuele.ascione@qualificagroup.com'],
        ['Mariarita', 'Balzamo', 'mariarita.balzamo@qualificagroup.com'],
        ['Maria', 'Bellini', 'maria.bellini@qualificagroup.com'],
        ['Gerardo', 'Bullaro', 'gerardo.bullaro@qualificagroup.com'],
        ['Marika', 'Caputo', 'marika.caputo@qualificagroup.com'],
        ['Antonio', 'Carbone', 'antonio.carbone@qualificagroup.com'],
        ['Rita', 'Carrese', 'rita.carrese@qualificagroup.com'],
        ['Nicolò', 'Caruso', 'nicolo.caruso@qualificagroup.com'],
        ['Umberto', 'Casiello', 'umberto.casiello@qualificagroup.com'],
        ['Anna', 'Castaldo', 'anna.castaldo@qualificagroup.com'],
        ['Valentina', 'Cavaliere', 'valentina.cavaliere@qualificagroup.com'],
        ['Raffaele', 'Centore', 'raffaele.centore@qualificagroup.it'],
        ['Jessica', 'Chentrens', 'jessica.chentrens@qualificagroup.com'],
        ['Patricia', 'Christovao', 'patricia.christovao@qualificagroup.com'],
        ['Luigi', 'Ciotola', 'luigi.ciotola@qualificagroup.com'],
        ['Luigi', 'Cirillo', 'luigi.cirillo@qualificagroup.com'],
        ['Lilly', 'Claderon', 'lilly.claderon@qualificagroup.com'],
        ['Diego', 'Cocchi', 'diego.cocchi@qualificagroup.com'],
        ['Fabrizio', 'Colletti', 'fabrizio.colletti@qualificagroup.com'],
        ['Consiglia', 'Cosentino', 'consiglia.cosentino@qualificagroup.com'],
        ['Emilianna', 'Credentino', 'emilianna.credentino@qualificagroup.com'],
        ['Gessica', 'Crispo', 'gessica.crispo@qualificagroup.com'],
        ['Romilda', 'Critelli', 'romilda.critelli@qualificagroup.com'],
        ['Dario', "D'Aleo", 'dario.daleo@qualificagroup.com'],
        ['Elio', "D'Ambra", 'elio.dambra@qualificagroup.it'],
        ['Maria', 'Dallara', 'maria.dallara@qualificagroup.com'],
        ['Federica', 'De Gennaro', 'federica.degennaro@qualificagroup.com'],
        ['Federica', 'De Lauro', 'federica.delauro@qualificagroup.com'],
        ['Laura', 'De Luca', 'laura.deluca@qualificagroup.com'],
        ['Antonio', 'De Martino', 'antonio.demartino@qualificagroup.com'],
        ['Pina', 'De Rosa', 'pina.derosa@qualificagroup.com'],
        ['Roberto', 'De Simone', 'roberto.desimone@qualificagroup.com'],
        ['Miriam', 'De Summa', 'miriam.desumma@qualificagroup.com'],
        ['Miriam', "Dell'Aversana", 'miriam.dellaversana@qualificagroup.com'],
        ['Giuseppe', 'Delle Cave', 'giuseppe.dellecave@qualificagroup.com'],
        ['Olimpia', 'Di Domenico', 'olimpia.didomenico@qualificagroup.com'],
        ['Anna', 'Di Maio', 'anna.dimaio@qualificagroup.com'],
        ['Francesco', 'Di Maio', 'francesco.dimaio@qualificagroup.com'],
        ['Claudia', 'Di Natale', 'claudia.dinatale@qualificagroup.com'],
        ['Raffaele', 'Distico', 'raffaele.distico@qualificagroup.com'],
        ['Nicola', 'Eliseo', 'nicola.eliseo@qualificagroup.com'],
        ['Giuliana', 'Ercolini', 'giuliana.ercolini@qualificagroup.com'],
        ['Marco', 'Esposito', 'marco.esposito@qualificagroup.com'],
        ['Mario', 'Esposito', 'mario.esposito@qualificagroup.com'],
        ['Nicoletta', 'Esposito', 'nicoletta.esposito@qualificagroup.com'],
        ['Deborah', 'Farina', 'deborah.farina@qualificagroup.com'],
        ['Gaetano', 'Farina', 'gaetano.farina@qualificagroup.com'],
        ['Antonino', 'Fasone', 'antonino.fasone@qualificagroup.com'],
        ['Annabella', 'Ferrante', 'annabella.ferrante@qualificagroup.com'],
        ['Enrico', 'Ferrante', 'enrico.ferrante@qualificagroup.com'],
        ['Giulia', 'Fiorentini', 'giulia.fiorentini@qualificagroup.com'],
        ['Ferdinando', 'Flagiello', 'ferdinando.flagiello@qualificagroup.com'],
        ['Antonio', 'Foglia', 'antonio.foglia@qualificagroup.com'],
        ['Giuseppe', 'Gallo', 'giuseppe.gallo@qualificagroup.com'],
        ['Giovanna', 'Gervasio', 'giovanna.gervasio@qualificagroup.com'],
        ['Giuseppe', 'Giagnorio', 'giuseppe.giagnorio@qualificagroup.com'],
        ['Annalisa', 'Giordano', 'annalisa.giordano@qualificagroup.com'],
        ['Alessandra', 'Grande', 'alessandra.grande@qualificagroup.com'],
        ['Edvige', 'Graziano', 'edvige.graziano@qualificagroup.com'],
        ['Gianluca', 'Greco', 'gianluca.greco@qualificagroup.com'],
        ['Marianna', 'Grimaldi', 'marianna.grimaldi@qualificagroup.com'],
        ['Alessio', 'Gualtieri', 'alessio.gualtieri@qualificagroup.com'],
        ['Nunzio', 'Guida', 'nunzio.guida@qualificagroup.com'],
        ['Maria', 'Iannotta', 'maria.iannotta@qualificagroup.com'],
        ['Francesco', 'Ienco', 'francesco.ienco@qualificagroup.com'],
        ['Amelia', 'Iorio', 'amelia.iorio@qualificagroup.com'],
        ['Lillo', 'Irrera', 'lillo.irrera@qualificagroup.com'],
        ['Graziella', 'La Piana', 'graziella.lapiana@qualificagroup.com'],
        ['Fabio', 'Lana', 'fabio.lana@qualificagroup.com'],
        ['Alessia', 'Luongo', 'alessia.luongo@qualificagroup.com'],
        ['Caterina', 'Maduni', 'caterina.maduni@qualificagroup.com'],
        ['Ivana', 'Mango', 'ivana.mango@qualificagroup.com'],
        ['Marzio', 'Martone', 'marzio.martone@qualificagroup.com'],
        ['Miriam', 'Mastro Martino', 'miriam.mastromartino@qualificagroup.com'],
        ['Francesca', 'Mauriello', 'francesca.mauriello@qualificagroup.com'],
        ['Silvia', 'Meccariello', 'silvia.meccariello@qualificagroup.com'],
        ['Ilaria', 'Miccichè', 'ilaria.micciche@qualificagroup.com'],
        ['Roberta', 'Mineo', 'roberta.mineo@qualificagroup.com'],
        ['Martina', 'Mosca', 'martina.mosca@qualificagroup.com'],
        ['Antonio', 'Nave', 'antonio.nave@qualificagroup.com'],
        ['Noemi', 'Nigliato', 'noemi.nigliato@qualificagroup.it'],
        ['Annalisa', 'Nocella', 'annalisa.nocella@qualificagroup.com'],
        ['Raffaele', 'Nocerino', 'raffaele.nocerino@qualificagroup.com'],
        ['Maria Lia', 'Oliva', 'marialia.oliva@qualificagroup.com'],
        ['Pasquale', 'Orsusanno', 'pasquale.orsusanno@qualificagroup.com'],
        ['Rosa', 'Pagliara', 'rosa.pagliara@qualificagroup.com'],
        ['Lia', 'Palladino', 'lia.palladino@qualificagroup.com'],
        ['Annarita', 'Palumbo', 'annarita.palumbo@qualificagroup.com'],
        ['Sabrina', 'Palumbo', 'sabrina.palumbo@qualificagroup.com'],
        ['Sara', 'Panella', 'sara.panella@qualificagroup.com'],
        ['Ida', 'Panico', 'ida.panico@qualificagroup.com'],
        ['Maria', 'Parisi', 'maria.parisi@qualificagroup.com'],
        ['Antonio Salvatore', 'Peluso', 'antoniosalvatore.peluso@qualificagroup.com'],
        ['Luigi', 'Perrotta', 'luigi.perrotta@qualificagroup.com'],
        ['Luigi Fabio', 'Pescosolido', 'luigifabio.pescosolido@qualificagroup.com'],
        ['Maria', 'Pezzella', 'maria.pezzella@qualificagroup.com'],
        ['Andrea', 'Pitruzzella', 'andrea.pitruzzella@qualificagroup.com'],
        ['Luca', 'Ponticelli', 'luca.ponticelli@qualificagroup.com'],
        ['Elio', 'Rettori', 'elio.rettori@qualificagroup.com'],
        ['Bernadetta', 'Romano', 'bernadetta.romano@qualificagroup.com'],
        ['Roberto', 'Rubino', 'roberto.rubino@qualificagroup.com'],
        ['Lidia', 'Russo', 'lidia.russo@qualificagroup.com'],
        ['Francesca', 'Russo Del Prete', 'francesca.russodelprete@qualificagroup.com'],
        ['Felice', 'Salomone', 'felice.salomone@qualificagroup.com'],
        ['Michele', 'Saracino', 'michele.saracino@qualificagroup.com'],
        ['Maria', 'Savarese', 'maria.savarese@qualificagroup.com'],
        ['Flavio', 'Scognamiglio', 'flavio.scognamiglio@qualificagroup.com'],
        ['Paola', 'Sena', 'paola.sena@qualificagroup.com'],
        ['Roberto', 'Sepe', 'roberto.sepe@qualificagroup.com'],
        ['Stefania', 'Silvestro', 'stefania.silvestro@qualificagroup.com'],
        ['Valentina', 'Sorrentino', 'valentina.sorrentino@qualificagroup.com'],
        ['Grazia', 'Stante', 'grazia.stante@qualificagroup.com'],
        ['Ilaria', 'Striano', 'ilaria.striano@qualificagroup.com'],
        ['Carmen', 'Taglialatela', 'carmen.taglialatela@qualificagroup.com'],
        ['Claudia', 'Testa', 'claudia.testa@qualificagroup.com'],
        ['Grazia', 'Triola', 'grazia.triola@qualificagroup.com'],
        ['Giuseppe', 'Tudisco', 'giuseppe.tudisco@qualificagroup.com'],
        ['Anna', 'Venere', 'anna.venere@qualificagroup.com'],
        ['Jessica', 'Virgolini', 'jessica.virgolini@qualificagroup.com'],
        ['Michele', 'Vitale', 'michele.vitale@qualificagroup.com'],
        ['Ilaria', 'Vitolo', 'ilaria.vitolo@qualificagroup.com'],
        ['Paola', 'Volpe', 'paola.volpe@qualificagroup.com'],
    ];
}
