<?php

namespace Database\Seeders\QualificaCatalog;

/**
 * The client's GOL training-course catalogue: the courses actually funded per
 * region, each with its total duration in hours. Split out of
 * QualificaCatalogSeeder as pure data (the seeder holds the logic, this file
 * holds the rows) — the list alone is well past the file-size budget.
 *
 * Keyed by the FULL product-category name, not by the bare region, so the
 * courses bind to the `GOL - <Regione>` nodes of
 * QualificaCatalogSeeder::CATALOG by identity: no string arithmetic to drift,
 * and renaming a region there breaks loudly here instead of silently dropping
 * its courses.
 *
 * `hours` is no longer written anywhere (user directive 2026-09-08 moved
 * "Ore complessive" from the product to the OFFERTA, where the operator
 * records it per deal): it survives as the DISCRIMINATOR of a course name
 * repeated inside one region — see CatalogProducts::disambiguate(). Course
 * names are user-facing domain values, kept in their original language, and
 * are the natural key for the idempotent per-category upsert.
 *
 * Two transcription rules applied to the source list, both user decisions:
 *   - a course quoting two durations ("150 / 140", 10 rows in Lombardia) keeps
 *     the FIRST;
 *   - a course name repeating inside one region with different durations (7
 *     rows in Abruzzo) is a DISTINCT course, disambiguated at seed time by
 *     QualificaTemplateSeeder::disambiguate() — the rows below stay verbatim.
 */
final class TrainingCourseCatalogue
{
    /**
     * Product category name => list of courses.
     *
     * @var array<string, list<array{name: string, hours: int}>>
     */
    public const array COURSES = [
        'GOL - Molise' => [
            ['name' => 'Alfabetizzazione Digitale', 'hours' => 60],
            ['name' => 'Word Base', 'hours' => 60],
            ['name' => 'Excel Base', 'hours' => 60],
            ['name' => 'Access Base', 'hours' => 60],
            ['name' => 'Inglese Livello B1', 'hours' => 60],
            ['name' => 'Italiano per Stranieri', 'hours' => 60],
            ['name' => 'Specialista Paghe e Contributi', 'hours' => 150],
            ['name' => 'Operatore Amministrativo Segretariale', 'hours' => 600],
            ['name' => 'Operatore di Cura e Pulizia di Spazi e Ambienti', 'hours' => 600],
            ['name' => 'Mediatore Interculturale', 'hours' => 600],
            ['name' => 'Competenze per Operatore Socio Sanitario', 'hours' => 580],
            ['name' => 'Operatore Socio Assistenziale', 'hours' => 600],
            ['name' => 'Tecnico di Cantiere Edile', 'hours' => 300],
            ['name' => 'Operatore Edile alle Infrastrutture', 'hours' => 600],
        ],
        'GOL - Abruzzo' => [
            ['name' => 'Informatica di Cittadinanza', 'hours' => 20],
            ['name' => 'Addetto alle Informazioni Ambientali e di Sostenibilità', 'hours' => 20],
            ['name' => 'Addetto alle Vendite di Prodotti Alimentari', 'hours' => 60],
            ['name' => 'Addetto Stipendi e Paghe', 'hours' => 40],
            ['name' => 'Assistente Familiare', 'hours' => 60],
            ['name' => 'Lingua Inglese Livello B1', 'hours' => 50],
            ['name' => 'Lingua Inglese Livello B2', 'hours' => 50],
            ['name' => 'Lingua Inglese Livello C1', 'hours' => 50],
            ['name' => 'Informatica e Competenze Digitali', 'hours' => 40],
            ['name' => 'Lingua Italiana per l\'Accesso al Lavoro per Cittadini Stranieri', 'hours' => 60],
            ['name' => 'Magazziniere', 'hours' => 66],
            ['name' => 'Mediatore Interculturale', 'hours' => 48],
            ['name' => 'Operatore Amministrativo Segretariale', 'hours' => 50],
            ['name' => 'Operatore Funebre/Necroforo', 'hours' => 36],
            ['name' => 'Somministrazione di Alimenti e Bevande', 'hours' => 124],
            ['name' => 'Accompagnatore Turistico', 'hours' => 55],
            ['name' => 'Addetto all\'Immissione e alla Gestione Digitale dei Dati', 'hours' => 60],
            ['name' => 'Pasticcere', 'hours' => 70],
            ['name' => 'Operatore di Confezione', 'hours' => 80],
            ['name' => 'Aiuto Cuoco', 'hours' => 50],
            ['name' => 'Operatore di Macelleria', 'hours' => 108],
            ['name' => 'Falegname', 'hours' => 70],
            ['name' => 'Modellista dell\'Abbigliamento', 'hours' => 85],
            ['name' => 'Operatore Agricolo delle Produzioni Vegetali', 'hours' => 42],
            ['name' => 'Cameriere di Sala, Bar e Attività di Banqueting', 'hours' => 60],
            ['name' => 'Pizzaiolo', 'hours' => 60],
            ['name' => 'Saldatore ad Arco Elettrico', 'hours' => 40],
            ['name' => 'Addetti alla Conduzione di Piattaforme di Lavoro Elevabili', 'hours' => 10],
            ['name' => 'Addetti alla Conduzione di Escavatori Idraulici', 'hours' => 16],
            ['name' => 'Addetti alla Conduzione di Carrelli Elevatori Semoventi', 'hours' => 12],
            ['name' => 'Addetti alla Conduzione di Gru per Autocarro', 'hours' => 12],
            ['name' => 'Barista', 'hours' => 328],
            ['name' => 'Serramentista', 'hours' => 268],
            ['name' => 'Sarto', 'hours' => 446],
            ['name' => 'Operatore dell\'Edilizia', 'hours' => 284],
            ['name' => 'Giuntista di Fibra Ottica', 'hours' => 219],
            ['name' => 'Manutentore del Verde', 'hours' => 180],
            ['name' => 'Operatore Ecologico', 'hours' => 256],
            ['name' => 'Tecnico della Sicurezza Informatica', 'hours' => 278],
            ['name' => 'Addetto alle Vendite di Prodotti Alimentari', 'hours' => 288],
            ['name' => 'Magazziniere', 'hours' => 260],
            ['name' => 'Operatore Funebre/Necroforo', 'hours' => 44],
            ['name' => 'Conduttore di Macchinari per il Movimento Terra', 'hours' => 174],
            ['name' => 'Operatore Agricolo di Allevamento Zootecnico', 'hours' => 256],
            ['name' => 'Operatore Macchine Utensili a Controllo Numerico', 'hours' => 316],
            ['name' => 'Addetto al Sistema di Gestione della Qualità', 'hours' => 312],
            ['name' => 'Saldatore ad Arco Elettrico', 'hours' => 256],
            ['name' => 'Posatore di Fibra Ottica', 'hours' => 208],
            ['name' => 'Tecnico Meccatronico delle Autoriparazioni', 'hours' => 500],
            ['name' => 'Installatore e Manutentore di Impianti Elettrici Civili', 'hours' => 381],
            ['name' => 'Aiuto Cuoco', 'hours' => 463],
            ['name' => 'Pizzaiolo', 'hours' => 370],
            ['name' => 'Tecnico della Valorizzazione dei Beni Culturali Ecclesiastici', 'hours' => 398],
            ['name' => 'Operatore Agricolo delle Produzioni Vegetali', 'hours' => 322],
        ],
        'GOL - Calabria' => [
            ['name' => 'Realizzazione di Opere Murarie e altre Lavorazioni Connesse', 'hours' => 150],
            ['name' => 'Preparazione e Somministrazione di Bevande e Snack', 'hours' => 150],
            ['name' => 'Installazione Impianti Elettrici e fotovoltaici', 'hours' => 150],
            ['name' => 'Installazione dell\'Impianto Elettrico', 'hours' => 150],
            ['name' => 'Gestione degli Ordini per il Magazzino e per i Fornitori Diretti', 'hours' => 160],
            ['name' => 'Assistenza di Base alla Clientela', 'hours' => 160],
            ['name' => 'Accogliere l\'Assistito e i Familiari all\'Interno delle Strutture Sanitarie', 'hours' => 160],
            ['name' => 'Operatore per la Realizzazione e Manutenzione di Giardini', 'hours' => 600],
            ['name' => 'Operatore per le Attività Relative alle Procedure Amministrative', 'hours' => 600],
        ],
        'GOL - Campania' => [
            ['name' => 'Manutentore del Verde', 'hours' => 200],
            ['name' => 'Apicoltore', 'hours' => 300],
            ['name' => 'Operatore di Panificazione e Produzione di Pasta', 'hours' => 300],
            ['name' => 'Operatore della Produzione di Prodotti di Panetteria', 'hours' => 300],
            ['name' => 'Addetto alle Lavorazioni Lattiero-Casearie', 'hours' => 250],
            ['name' => 'Addetto al Confezionamento dei Prodotti Alimentari', 'hours' => 250],
            ['name' => 'Tecnico di Coordinamento del Cantiere', 'hours' => 300],
            ['name' => 'Operatore Edile alla Posa di Pavimenti e Rivestimenti', 'hours' => 180],
            ['name' => 'Installatore di Materiali di Isolamento Termico ed Acustico', 'hours' => 300],
            ['name' => 'Operatore alla Conduzione di Macchine Scavo Movimento Terra', 'hours' => 200],
            ['name' => 'Tecnico Specializzato BIM Specialist', 'hours' => 300],
            ['name' => 'Operatore Edile alla Carpenteria', 'hours' => 180],
            ['name' => 'Operatore Edile', 'hours' => 180],
            ['name' => 'Installatore e Manutentore di Sistemi Fotovoltaici', 'hours' => 100],
            ['name' => 'Installazione e Manutenzione di Impianti Elettrici', 'hours' => 300],
            ['name' => 'Gestione Magazzino Spedizioni e Logistica', 'hours' => 120],
            ['name' => 'Installazione e Manutenzione di Impianti Termo Idraulici', 'hours' => 300],
            ['name' => 'Tecnico di Spedizione Trasporti e Logistica', 'hours' => 300],
            ['name' => 'Agente e Rappresentante di Commercio', 'hours' => 100],
            ['name' => 'Addetto all\'Allestimento e Rifornimento degli Scaffali', 'hours' => 250],
            ['name' => 'SMA-SAB (ex REC)', 'hours' => 120],
            ['name' => 'Tecnico Hardware', 'hours' => 300],
            ['name' => 'Tecnico Software', 'hours' => 300],
            ['name' => 'Competenze Digitali di Base', 'hours' => 60],
            ['name' => 'Configurare un Sistema di Archiviazione dei Dati Personali', 'hours' => 120],
            ['name' => 'Web Designer', 'hours' => 300],
            ['name' => 'ASACOM - Assistente Autonomia e Comunicazione Persone Disabili', 'hours' => 500],
            ['name' => 'OSA - Operatore Socio Assistenziale', 'hours' => 300],
            ['name' => 'DSA - Tutor Didattico per Studenti con Difficoltà di Apprendimento', 'hours' => 300],
            ['name' => 'OPI - Operatore Prima Infanzia', 'hours' => 300],
            ['name' => 'OAED - Operatore all\'Assistenza Educativa ai Disabili', 'hours' => 300],
            ['name' => 'Tecnico Esperto nella Gestione di Struttura Socio Sanitaria', 'hours' => 300],
            ['name' => 'Tecnico dell\'Assistenza Domiciliare ai Minori', 'hours' => 300],
            ['name' => 'Animatore Sociale', 'hours' => 300],
            ['name' => 'Mediatore Culturale', 'hours' => 400],
            ['name' => 'Tecnico dell\'Assistenza alla Genitorialità', 'hours' => 300],
            ['name' => 'Realizzazione di Trattamenti Dermo Estetici del Viso', 'hours' => 120],
            ['name' => 'Realizzazione di Trattamenti di Trucco e Visagismo', 'hours' => 120],
            ['name' => 'Operatore Olistico del Benessere', 'hours' => 400],
            ['name' => 'Operatore di Animal Care', 'hours' => 250],
            ['name' => 'Collaboratore Domestico - COLF', 'hours' => 200],
            ['name' => 'Operatore di Tatuaggio e Piercing', 'hours' => 500],
            ['name' => 'Pratica dei Trattamenti di Massaggio Antistress', 'hours' => 120],
            ['name' => 'Realizzazione di Trattamenti di Depilazione dei Peli del Corpo', 'hours' => 120],
            ['name' => 'Realizzazione di Trattamenti di Cura e Ricostruzione Unghie', 'hours' => 120],
            ['name' => 'Truccatore dello Spettacolo', 'hours' => 400],
            ['name' => 'Tecnico della Ripresa e del Montaggio Audiovisivo', 'hours' => 300],
            ['name' => 'Operatore del Servizio di Sala Cameriere', 'hours' => 300],
            ['name' => 'Operatore di Agenzia Viaggio', 'hours' => 300],
            ['name' => 'Operatore Cucina - Cuoco', 'hours' => 400],
            ['name' => 'Operatore del Servizio Bar', 'hours' => 300],
            ['name' => 'Segretario - Coordinatore Amministrativo', 'hours' => 300],
            ['name' => 'Operatore Amministrativo Contabile', 'hours' => 300],
            ['name' => 'Social Media Manager', 'hours' => 300],
            ['name' => 'Tecnico Esperto in Organizzazione di Eventi', 'hours' => 300],
            ['name' => 'Operatore della Sanificazione', 'hours' => 200],
            ['name' => 'Grafico Pubblicitario', 'hours' => 300],
            ['name' => 'Inglese per la Gestione Amministrativa', 'hours' => 120],
            ['name' => 'Operatore Call Center Inbound', 'hours' => 250],
            ['name' => 'Team Leader di Call Center', 'hours' => 300],
            ['name' => 'Operatore delle Attività di Vigilanza e Sicurezza', 'hours' => 300],
            ['name' => 'Addetto ai Servizi di Controllo Intrattenimento e Spettacolo', 'hours' => 120],
            ['name' => 'Sviluppo del Modello di Customer Care', 'hours' => 120],
            ['name' => 'Sviluppo di Soluzioni Migliorative di Processi e Output Aziendali', 'hours' => 120],
            ['name' => 'Addetto alla Cura e Pulizia di Spazi ed Ambienti', 'hours' => 200],
            ['name' => 'Tecnico della Gestione d\'Impresa di Pulizia', 'hours' => 300],
            ['name' => 'Tecnico Esperto nella Partecipazione a Gare d\'Appalto', 'hours' => 300],
            ['name' => 'Operatore Segretariale', 'hours' => 200],
        ],
        'GOL - Lombardia' => [
            ['name' => 'Addetto alla Segreteria', 'hours' => 150],
            ['name' => 'Addetto alle Vendite e Gestione della Cassa', 'hours' => 150],
            ['name' => 'Addetto alle Pulizie e Sanificazione', 'hours' => 150],
            ['name' => 'Operatore di Magazzino della Logistica e della Spedizione', 'hours' => 130],
            ['name' => 'Operatore al Confezionamento Prodotti', 'hours' => 150],
            ['name' => 'Disegnatore Meccanico AutoCAD', 'hours' => 150],
            ['name' => 'Installatore e Manutentore Meccanico', 'hours' => 150],
            ['name' => 'Informatica di Base', 'hours' => 60],
            ['name' => 'Italiano per Stranieri', 'hours' => 60],
            ['name' => 'Conduzione di Carrelli Elevatori Semoventi con Conducente', 'hours' => 12],
            ['name' => 'SMA - SAB Somministrazione di Alimenti e Bevande', 'hours' => 130],
            ['name' => 'Agenti e Rappresentanti di Commercio', 'hours' => 130],
            ['name' => 'FER - Installatore e Manutentore Straordinario di Impianti Energetici', 'hours' => 80],
            ['name' => 'Assistente Familiare', 'hours' => 160],
            ['name' => 'Tecnico Amministrazione del Personale', 'hours' => 150],
            ['name' => 'Inglese per il Lavoro', 'hours' => 60],
            ['name' => 'Inglese Base', 'hours' => 60],
            ['name' => 'Inglese Intermedio', 'hours' => 60],
            ['name' => 'Animatore di Comunità', 'hours' => 150],
            ['name' => 'Animatore per Anziani', 'hours' => 150],
            ['name' => 'Animatore di Ludoteca', 'hours' => 150],
            ['name' => 'Consulente Immagine con Specializzazione Trucco Skin Care', 'hours' => 150],
            ['name' => 'Beauty Coach', 'hours' => 150],
            ['name' => 'Consulente di Immagine', 'hours' => 150],
            ['name' => 'Impiegato Contabile Amministrativo', 'hours' => 150],
            ['name' => 'Content and Social Media Manager', 'hours' => 150],
            ['name' => 'Intelligenza Artificiale e Digital Contents Principi Fondamentali', 'hours' => 150],
            ['name' => 'Introduzione al Counseling', 'hours' => 150],
            ['name' => 'Digital Marketing', 'hours' => 150],
            ['name' => 'Esperto in Percorsi Musicali e Multimediali', 'hours' => 150],
            ['name' => 'Operatore Sociale di Strada', 'hours' => 150],
            ['name' => 'Interprete di Lingua dei Segni', 'hours' => 150],
            ['name' => 'Ricostruzione e Decorazione delle Unghie', 'hours' => 140],
            ['name' => 'Makeup Artist', 'hours' => 150],
            ['name' => 'Operatore del Makeup', 'hours' => 150],
            ['name' => 'Operatore Olistico del Benessere', 'hours' => 150],
            ['name' => 'Sommelier', 'hours' => 150],
            ['name' => 'Cuoco', 'hours' => 150],
            ['name' => 'Addetto al Magazzino con Patentino del Muletto', 'hours' => 72],
            ['name' => 'Addetto al Servizio di Sala', 'hours' => 150],
            ['name' => 'Addetto al Servizio di Sala Corso Base', 'hours' => 50],
            ['name' => 'Corso di Pasticceria', 'hours' => 150],
            ['name' => 'Barman - Corso Base', 'hours' => 50],
            ['name' => 'Barman - Corso Intermedio Mixology', 'hours' => 50],
            ['name' => 'Barman', 'hours' => 150],
            ['name' => 'Modellistica e Sartoria', 'hours' => 140],
            ['name' => 'Informatica Livello Intermedio', 'hours' => 60],
            ['name' => 'Responsabile Sistemi Informativi', 'hours' => 150],
            ['name' => 'Payroll Specialist Gestione Paghe e Contributi', 'hours' => 150],
            ['name' => 'Ricostruzione e Decorazione delle Unghie - Corso Base', 'hours' => 60],
            ['name' => 'Operatore del Makeup Corso Base', 'hours' => 80],
            ['name' => 'Cyber Security', 'hours' => 64],
            ['name' => 'Addetto alla Segreteria di Studio Medico', 'hours' => 100],
            ['name' => 'Addetto alle Attività di Informazione ed Accoglienza Turistica', 'hours' => 140],
            ['name' => 'Addetto Pulizie', 'hours' => 70],
            ['name' => 'Graphic e Web Designer', 'hours' => 140],
            ['name' => 'Addetta/o ai Servizi Mensa in Ristorazione Collettiva', 'hours' => 140],
            ['name' => 'Programmatore Turistico', 'hours' => 140],
            ['name' => 'Addetto alla Vendita di Lusso', 'hours' => 50],
            ['name' => 'Addetto Paghe e Contributi', 'hours' => 40],
            ['name' => 'Operatore Caf Formazione Preliminare', 'hours' => 40],
            ['name' => 'Grafica e Immagini - Base', 'hours' => 40],
            ['name' => 'Tecniche Base di Giardinaggio', 'hours' => 40],
            ['name' => 'Tecniche di Social Media Marketing', 'hours' => 40],
        ],
        'GOL - Lazio' => [
            ['name' => 'Comunicazione Interpersonale', 'hours' => 50],
            ['name' => 'Inglese per il Lavoro d\'Ufficio', 'hours' => 50],
            ['name' => 'Italiano per Stranieri', 'hours' => 50],
            ['name' => 'Office Avanzato', 'hours' => 50],
            ['name' => 'Corso di Lingua Inglese B1', 'hours' => 50],
            ['name' => 'Sviluppo e Gestione Siti Web', 'hours' => 150],
            ['name' => 'Digital Marketing', 'hours' => 150],
            ['name' => 'Patente Europea del Computer Corso Preparatorio', 'hours' => 150],
            ['name' => 'Digicomp 2.1 Alfabetizzazione Digitale', 'hours' => 150],
            ['name' => 'Informatica per l\'Ufficio', 'hours' => 150],
            ['name' => 'Inglese Base', 'hours' => 40],
            ['name' => 'Inglese Intermedio', 'hours' => 40],
            ['name' => 'Office 365 Base', 'hours' => 40],
            ['name' => 'Office 365 Intermedio', 'hours' => 40],
            ['name' => 'Personal Branding e Team Working', 'hours' => 40],
            ['name' => 'Segreteria con Competenze Digitali', 'hours' => 40],
            ['name' => 'Comprendere e Interagire con l\'Intelligenza Artificiale', 'hours' => 40],
            ['name' => 'Lingua Italiana per Stranieri', 'hours' => 40],
            ['name' => 'Comunicare con le Tecnologie Digitali', 'hours' => 40],
            ['name' => 'Gestione Amministrativa del Magazzino', 'hours' => 40],
            ['name' => 'Mediatore Interculturale', 'hours' => 507],
            ['name' => 'Manutentore del Verde', 'hours' => 300],
            ['name' => 'OSS - Operatore Socio Sanitario', 'hours' => 1012],
            ['name' => 'ASO - Assistente Studio Odontoiatrico', 'hours' => 700],
            ['name' => 'Web Developer', 'hours' => 356],
            ['name' => 'Operatore Educativo per l\'Autonomia e la Comunicazione', 'hours' => 400],
            ['name' => 'Operatore al Servizio Bar (Barista/Barman)', 'hours' => 370],
            ['name' => 'Operatore Assistenza Clienti', 'hours' => 300],
            ['name' => 'Tecnico dei Servizi Turistico Ricettivi', 'hours' => 370],
            ['name' => 'Operatore della Ristorazione Aiuto - Cuoco', 'hours' => 410],
            ['name' => 'Addetto Paghe e Contributi', 'hours' => 308],
            ['name' => 'Animatore Sociale', 'hours' => 520],
            ['name' => 'Operatore Amministrativo Segretariale', 'hours' => 430],
            ['name' => 'Operatore al Servizio Sala', 'hours' => 292],
            ['name' => 'Assistente Familiare', 'hours' => 340],
        ],
        'GOL - Umbria' => [
            ['name' => 'Competenze Tecniche per Recupero e Smaltimento dei Rifiuti', 'hours' => 80],
            ['name' => 'Misurazione e Controllo della Qualità Aziendale', 'hours' => 44],
            ['name' => 'Competenze per la Comunicazione e il Marketing Aziendale', 'hours' => 80],
            ['name' => 'Operatore per il Trattamento, il Recupero e lo Smaltimento Rifiuti', 'hours' => 210],
            ['name' => 'Addetto Qualificato alle Lavorazioni Edili - Pittore', 'hours' => 268],
            ['name' => 'Tecnico del Marketing Turistico', 'hours' => 203],
            ['name' => 'Corso di preparazione per ICDL Full Standard', 'hours' => 40],
            ['name' => 'Comunicazione Digitale', 'hours' => 40],
        ],
    ];
}
